### ISSUE TITLE
Centos 8 support

### ISSUE THREAD

**Issue by amrBV** [aker-gateway/Aker#99]
How can i set up Aker on Centos 8 ? as the current steps don't work.

**Comment by EoleDev** [comment]
Hi @amrBV 
Here is some instructions which could help you install it on centos 8 : 
`yum install redis python2 python2-pip`
`git clone https://github.com/aker-gateway/Aker.git /usr/bin/aker/`

modify /usr/bin/aker/requirements.txt
`  line "urwid"`
`  to line "urwid == 1.1.1"`

`pip2 install -r /usr/bin/aker/requirements.txt`

`chmod 755 /usr/bin/aker/aker.py`
`chmod 755 /usr/bin/aker/akerctl.py`

`mkdir /var/log/aker`
`chmod 777 /var/log/aker`
`touch /var/log/aker/aker.log`
`chmod 777 /var/log/aker/aker.log`

Enforce aker on all users but root, edit sshd_config

`Match Group *,!root`
`ForceCommand /usr/bin/aker/aker.py`

`systemctl restart sshd`
`systemctl restart redis`

I made you modify the requirements.txt due to a patch currently in discussion see #96
If you encounter an issue, don't hesitate to ask. These instructions are not tested.

**Comment by amrBV** [comment]
I had to add 
`yum install python2-dev`
now when i try to run `/usr/bin/aker/aker.py` i get the following message:
/usr/bin/env: ‘python’: No such file or directory
and this is the result of `whereis python`
`python: /usr/bin/python2.7 /usr/bin/python2.7-config /usr/lib/python3.6 /usr/lib/python2.7 /usr/lib64/python2.7 /usr/lib64/python3.6 /usr/include/python3.6m /usr/include/python2.7 /usr/share/man/man1/python.1.gz`

**Comment by EoleDev** [comment]
Of course, I forgot it...
You should replace the line 
`#!/usr/bin/env python`
which is at the top of the file /usr/bin/aker/aker.py, by the line
`#!/usr/bin/env python2.7`

**Comment by amrBV** [comment]
I got this error
`Traceback (most recent call last):
  File "/usr/bin/aker/aker.py", line 174, in <module>
    Aker().build_tui()
  File "/usr/bin/aker/aker.py", line 111, in __init__
    config = Configuration(config_file)
  File "/usr/bin/aker/aker.py", line 60, in __init__
    self.log_level = self.configparser.get('General', 'log_level')
  File "/usr/lib/python2.7/site-packages/backports/configparser/__init__.py", line 858, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1228, in _unify_values
    raise NoSectionError(section)
backports.configparser.NoSectionError: No section: 'General'`

**Comment by EoleDev** [comment]
You need to take the official documentation, bypass the common steps, and do the steps
for the IDP you want (freeipa/json..).
It seems you have no configuration file !

**Comment by amrBV** [comment]
It is working now, i didn't have any configuration file.
